process KALLISTO_QUANT {
    tag "$meta.id"
    // clusterOptions = '-S /bin/bash'
    label 'kallisto_quant', 'per_sample'

    memory {
        if (meta.single_end) {
          fileSize = reads.size() / (1024 * 1024 * 1024)   // GB
        } else {
          fileSize = reads[0].size() / (1024 * 1024 * 1024) // GB
        }
        if (fileSize < 15){
          return 10.GB
        } else {
          return 7.GB * (1 + (fileSize*0.25))
        }
    }

    publishDir "${params.results_directory}/kallisto", mode: 'copy'

    input:
    tuple val(meta), path(reads)
    path transcript_index

    output:
    // H5 optional so zero-read samples don't need a fake HDF5
    tuple val(meta), path("${meta.id}.kallisto.abundance.h5") , emit: abundance_h5, optional: true
    tuple val(meta), path("${meta.id}.kallisto.abundance.tsv"), emit: abundance_tsv
    tuple val(meta), path("${meta.id}.kallisto.run_info.json"), emit: json_info,   optional: true
    tuple val(meta), path("${meta.id}.kallisto.log")          , emit: log,         optional: true

    script:
    if (meta.single_end) {
        """
        set -euo pipefail

        PREFIX="${meta.id}"

        count_reads () {
          local f="\$1"
          if [[ "\$f" == *.gz ]]; then
            local l
            l=\$(zcat -f -- "\$f" 2>/dev/null | wc -l || echo 0)
            echo \$(( l / 4 ))
          else
            local l
            l=\$(wc -l < "\$f" 2>/dev/null || echo 0)
            echo \$(( l / 4 ))
          fi
        }

        make_empty_outputs () {
          local why="\$1"
          echo -e "target_id\\tlength\\teff_length\\test_counts\\ttpm" > "\${PREFIX}.kallisto.abundance.tsv"
          cat > "\${PREFIX}.kallisto.run_info.json" <<JSON
{ "kallisto_status": "skipped",
  "reason": "\${why}",
  "n_processed": 0,
  "n_pseudoaligned": 0,
  "note": "Generated by pipeline guard for zero-read inputs." }
JSON
          echo "[kallisto] \${why}" > "\${PREFIX}.kallisto.log"
        }

        post_run_safety () {
          if [[ ! -s "\${PREFIX}/abundance.tsv" ]]; then
            make_empty_outputs "kallisto produced no abundance.tsv; emitting empty outputs"
          else
            mv "\${PREFIX}/abundance.tsv" "\${PREFIX}.kallisto.abundance.tsv"
            if [[ -s "\${PREFIX}/abundance.h5" ]]; then
              mv "\${PREFIX}/abundance.h5" "\${PREFIX}.kallisto.abundance.h5"
            fi
            if [[ -s "\${PREFIX}/run_info.json" ]]; then
              mv "\${PREFIX}/run_info.json" "\${PREFIX}.kallisto.run_info.json"
            fi
          fi
        }

        R=\$(count_reads "${reads}")
        if [[ "\$R" -eq 0 ]]; then
          make_empty_outputs "No reads detected in input (single-end); skipping kallisto."
          exit 0
        fi

        kallisto quant --index ${transcript_index} --output-dir "\${PREFIX}" -t ${task.cpus} \\
                       --single -l ${params.fragment_length_mean} -s ${params.fragment_length_std} ${reads} \\
                       > "\${PREFIX}.kallisto.log" 2>&1 || true

        post_run_safety
        """
    } else {
        """
        set -euo pipefail

        PREFIX="${meta.id}"

        count_reads () {
          local f="\$1"
          if [[ "\$f" == *.gz ]]; then
            local l
            l=\$(zcat -f -- "\$f" 2>/dev/null | wc -l || echo 0)
            echo \$(( l / 4 ))
          else
            local l
            l=\$(wc -l < "\$f" 2>/dev/null || echo 0)
            echo \$(( l / 4 ))
          fi
        }

        make_empty_outputs () {
          local why="\$1"
          echo -e "target_id\\tlength\\teff_length\\test_counts\\ttpm" > "\${PREFIX}.kallisto.abundance.tsv"
          cat > "\${PREFIX}.kallisto.run_info.json" <<JSON
{ "kallisto_status": "skipped",
  "reason": "\${why}",
  "n_processed": 0,
  "n_pseudoaligned": 0,
  "note": "Generated by pipeline guard for zero-read inputs." }
JSON
          echo "[kallisto] \${why}" > "\${PREFIX}.kallisto.log"
        }

        post_run_safety () {
          if [[ ! -s "\${PREFIX}/abundance.tsv" ]]; then
            make_empty_outputs "kallisto produced no abundance.tsv; emitting empty outputs"
          else
            mv "\${PREFIX}/abundance.tsv" "\${PREFIX}.kallisto.abundance.tsv"
            if [[ -s "\${PREFIX}/abundance.h5" ]]; then
              mv "\${PREFIX}/abundance.h5" "\${PREFIX}.kallisto.abundance.h5"
            fi
            if [[ -s "\${PREFIX}/run_info.json" ]]; then
              mv "\${PREFIX}/run_info.json" "\${PREFIX}.kallisto.run_info.json"
            fi
          fi
        }

        R1=\$(count_reads "${reads[0]}")
        R2=\$(count_reads "${reads[1]}")
        if [[ "\$R1" -eq 0 || "\$R2" -eq 0 ]]; then
          make_empty_outputs "One or both mates contain zero reads (R1=\$R1, R2=\$R2); skipping kallisto."
          exit 0
        fi

        kallisto quant --index ${transcript_index} --output-dir "\${PREFIX}" -t ${task.cpus} \\
                       "${reads[0]}" "${reads[1]}" \\
                       > "\${PREFIX}.kallisto.log" 2>&1 || true

        post_run_safety
        """
    }
}
