---
outdir: /c4/home/danb/rna_seq_testing_outs/run1
cohort_name: plateTest
samples:
    mini_CONTROL_jurkat_PlateP27:
        R1: /krummellab/data1/arrao/projects/mini_fastqs/Plate27Rnaseq/mini_CONTROL_jurkat_PlateP27_S12_L003_R1_001.fastq.gz 
        R2: /krummellab/data1/arrao/projects/mini_fastqs/Plate27Rnaseq/mini_CONTROL_jurkat_PlateP27_S12_L003_R2_001.fastq.gz 
    mini_IPICRC099_T1_rna_tcell:
        R1: /krummellab/data1/arrao/projects/mini_fastqs/Plate27Rnaseq/mini_IPICRC099_T1_rna_tcell_S92_L003_R1_001.fastq.gz 
        R2: /krummellab/data1/arrao/projects/mini_fastqs/Plate27Rnaseq/mini_IPICRC099_T1_rna_tcell_S92_L003_R2_001.fastq.gz 
