## Specific to users of the pipeline - users must modify ##
depooling:
  input_files:
    - "/krummellab/data1/amazzara/tutorial_lib_sep/data/single_cell_GEX/processed/TEST-POOL-DM2-SCG1/automated_processing/TEST-POOL-DM2-SCG1_raw.rds"
  output_files:
    - "/krummellab/data1/amazzara/tutorial_lib_sep/data/single_cell_GEX/processed/TEST-POOL-DM2-SCG1/automated_processing/TEST-POOL-DM2-SCG1_out.rds"

## Users do not need to modify ##
container:
  r:  "/krummellab/data1/singularity_images/RSingleCell/v4/RSingleCell.sif"
  python: "/krummellab/data1/singularity_images/cytof/v3/cytof.sif"