configfile: "pipelines/de-pooling/config.yaml"

rule depooling:
    input:
        input_files = config["depooling"]["input_files"]
    output:
        directory(config["depooling"]["output_dir"])
    singularity:
        config["container"]["r"]
    params:
        script="bin/de_pool.R",
        container_input_files = config["depooling"]["container_input_files"],
        container_out_dir = config["depooling"]["container_output_dir"]
    shell:
        """
        Rscript {params.script} {params.container_input_files} {params.container_out_dir}
        """