configfile: "pipelines/de-pooling/config.yaml"

rule depooling:
    input:
        input_files = config["depooling"]["input_files"]
    output:
        output_file = config["depooling"]["output_file"]
    singularity:
        config["container"]["r"]
    params:
        script="bin/de_pool.R",
        container_input_files = config["depooling"]["container_input_files"],
        container_out_file = config["depooling"]["container_output_file"]
    shell:
        """
        Rscript {params.script} {params.container_input_files} {params.container_out_file}
        """