input:
    DM1_SCG1_raw: "/krummellab/data1/amazzara/tutorial_lib_sep/data/single_cell_GEX/processed/TEST-POOL-DM1-SCG1/automated_processing/TEST-POOL-DM1-SCG1_raw.rds"
    DM1_SCG2_raw: "/krummellab/data1/amazzara/tutorial_lib_sep/data/single_cell_GEX/processed/TEST-POOL-DM1-SCG2/automated_processing/TEST-POOL-DM1-SCG2_raw.rds"
output_dir: "/krummellab/data1/amazzara/tutorial_lib_sep/data/single_cell_GEX/processed/depooled/"
container:
  r:  "/krummellab/data1/singularity_images/RSingleCell/v4/RSingleCell.sif"
  python: "/krummellab/data1/singularity_images/cytof/v3/cytof.sif"