configfile: "pipelines/depooling/config.yaml"

rule all:
    input:
        expand(config["output_dir"] + "{sample_tag}/", sample_tag=list(config["input"].keys()))

rule de_pool:
    input:
        lambda wildcards: config["input"][wildcards.sample_tag]
    output:
        directory(config["output_dir"] + "{sample_tag}/")
    singularity:
        config["container"]["r"]
    params:
        script="bin/de_pool.R"
    shell:
        """
        Rscript {params.script} {input} {output}
        """