configfile: "pipelines/de-pooling/config.yaml"

rule depooling:
    input:
        input_files = config["depooling"]["input_files"]
    output:
        directory(config["depooling"]["output_dir"])
    singularity:
        config["container"]["r"]
    params:
        script="bin/de_pool.R",
    shell:
        """
        Rscript {params.script} {input.input_files} {output}
        """