# Reference set (matches hg38_p13_references.config)
reference_directory: "/krummellab/data1/DSCoLab/references/human/hg38_p13/ncbi_refseq"
genome:              "/krummellab/data1/DSCoLab/references/human/hg38_p13/ncbi_refseq/GCF_000001405.39_GRCh38.p13_genomic.fna"
genome_idx:          "/krummellab/data1/DSCoLab/references/human/hg38_p13/ncbi_refseq/GCF_000001405.39_GRCh38.p13_genomic.fna.fai"
genome_dict:         "/krummellab/data1/DSCoLab/references/human/hg38_p13/ncbi_refseq/GCF_000001405.39_GRCh38.p13_genomic.dict"
genome_dir:          "/krummellab/data1/DSCoLab/references/human/hg38_p13/ncbi_refseq/star_index"
gtf:                 "/krummellab/data1/DSCoLab/references/human/hg38_p13/ncbi_refseq/GCF_000001405.39_GRCh38.p13_genomic.gtf"
transcript_fasta:    "/krummellab/data1/DSCoLab/references/human/hg38_p13/ncbi_refseq/rsem_genome.transcripts.fa"
transcript_index:    "/krummellab/data1/DSCoLab/references/human/hg38_p13/ncbi_refseq/kallisto_index"
dbsnp:               "/krummellab/data1/DSCoLab/references/human/hg38_p13/ncbi_refseq/GCF_000001405.39.gz"
dbsnp_tbi:           "/krummellab/data1/DSCoLab/references/human/hg38_p13/ncbi_refseq/GCF_000001405.39.gz.tbi"
gene_mapper:         "/krummellab/data1/DSCoLab/references/human/hg38_p13/ncbi_refseq/GCF_000001405.39.gz.tbi"
contig_format_map:   "/krummellab/data1/DSCoLab/references/human/hg38_p13/ncbi_refseq/hg38.p13.chromAlias.txt"
rrna_db_file:        "/krummellab/data1/DSCoLab/references/human/hg38_p13/ncbi_refseq/rrna_db.txt"
