# Example alternative reference set (matches references.config)
reference_directory: "/krummellab/data1/DSCoLab/references/human/hg38_p14/ncbi_refseq"
genome:              "/krummellab/data1/DSCoLab/references/human/hg38_p14/ncbi_refseq/GCF_000001405.40_GRCh38.p14_genomic.fna"
genome_idx:          "/krummellab/data1/DSCoLab/references/human/hg38_p14/ncbi_refseq/GCF_000001405.40_GRCh38.p14_genomic.fna.fai"
genome_dict:         "/krummellab/data1/DSCoLab/references/human/hg38_p14/ncbi_refseq/GCF_000001405.40_GRCh38.p14_genomic.dict"
genome_dir:          "/krummellab/data1/DSCoLab/references/human/hg38_p14/ncbi_refseq/star_index"
gtf:                 "/krummellab/data1/DSCoLab/references/human/hg38_p14/ncbi_refseq/genomic.gtf"
transcript_fasta:    "/krummellab/data1/DSCoLab/references/human/hg38_p14/ncbi_refseq/rsem_genome.transcripts.fa"
transcript_index:    "/krummellab/data1/DSCoLab/references/human/hg38_p14/ncbi_refseq/kallisto_index"
dbsnp:               "/krummellab/data1/DSCoLab/references/human/hg38_p14/ncbi_refseq/GCF_000001405.40.gz"
dbsnp_tbi:           "/krummellab/data1/DSCoLab/references/human/hg38_p14/ncbi_refseq/GCF_000001405.40.gz.tbi"
gene_mapper:         "/krummellab/data1/DSCoLab/references/human/hg38_p14/ncbi_refseq/GCF_000001405.40.gz.tbi"
contig_format_map:   "/krummellab/data1/DSCoLab/references/human/hg38_p14/ncbi_refseq/chromAlias.txt"
rrna_db_file:        "/krummellab/data1/DSCoLab/references/human/hg38_p14/ncbi_refseq/rrna_db.txt"